## Tes
- Membuat Data Dummy untuk Asisten Mata Kuliah karena kami tidak dapat menemukan dataset yang sesuai dengan proyek di internet
- Imputasi data acak dengan aturan sbb:
  - Data nilai tugas proyek 1 diacak dari E s/d A
  - Distribusi rentang nilai dapat dilihat di bawah
  - Topik skripsi diambil dari 3 matkul teratas diacak

  - Toko Komputer Masa Depan


- Panduan Pengisian Nilai	
  - E	1
  - D- 2
  - D	3
  - D+ 4
  - C- 5
  - C	6
  - C+ 7
  - B- 8
  - B	9
  - B+ 10
  - A- 11
  - A	12

In [1]:
import pandas as pd
from random import randint

In [2]:
df = pd.read_csv("data-dummy-mentah.csv")
df

,No Mhs,Kalkulus 1 TP1,Kalkulus TP2,Kalkulus 1 UTS,Kalkulus 1 UAS,Kalkulus 1 Rata-Rata,Data Sci IoT TP1,Data Sci IoT TP2,Data Sci IoT UTS,Data Sci IoT UAS,...,Pemrograman Mobile TP2,Pemrograman Mobile UTS,Pemrograman Mobile UAS,Pemrograman Mobile Rata-Rata,Blockchain TP1,Blockchain TP2,Blockchain UTS,Blockchain UAS,Blockchain Rata-Rata,Topik Skripsi
0,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
1,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
2,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
3,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
4,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
996,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
997,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
998,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES
999,1,1,1,1,1,2,1,1,1,1,...,1,1,1,2,1,1,1,1,2,TES

In [3]:
for i in range(1,len(df.columns),5):
    try:
        print(df.iloc[:,i:i+5])
        print('ENDLINE')
    except:
        break

     Kalkulus 1 TP1  Kalkulus TP2  Kalkulus 1 UTS  Kalkulus 1 UAS  \
0                 1             1               1               1
1                 1             1               1               1
2                 1             1               1               1
3                 1             1               1               1
4                 1             1               1               1
..              ...           ...             ...             ...
995               1             1               1               1
996               1             1               1               1
997               1             1               1               1
998               1             1               1               1
999               1             1               1               1

     Kalkulus 1 Rata-Rata
0                       2
1                       2
2                       2
3                       2
4                       2
..                    ...
995                     2
996                     2
997                     2
998                     2
999                     2

[1000 rows x 5 columns]
ENDLINE
     Data Sci IoT TP1  Data Sci IoT TP2  Data Sci IoT UTS  Data Sci IoT UAS  \
0                   1                 1                 1                 1
1                   1                 1                 1                 1
2                   1                 1                 1                 1
3                   1                 1                 1                 1
4                   1                 1                 1                 1
..                ...               ...               ...               ...
995                 1                 1                 1                 1
996                 1                 1                 1                 1
997                 1                 1                 1                 1
998                 1                 1                 1                 1
999                 1                 1                 1                 1

     Data Sci IoT Rata-Rata
0                         2
1                         2
2                         2
3                         2
4                         2
..                      ...
995                       2
996                       2
997                       2
998                       2
999                       2

[1000 rows x 5 columns]
ENDLINE
     Keamanan Komp TP1  Keamanan Komp TP2  Keamanan Komp UTS  \
0                    1                  1                  1
1                    1                  1                  1
2                    1                  1                  1
3                    1                  1                  1
4                    1                  1                  1
..                 ...                ...                ...
995                  1                  1                  1
996                  1                  1                  1
997                  1                  1                  1
998                  1                  1                  1
999                  1                  1                  1

     Keamanan Komp UAS  Keamanan Komp Rata-Rata
0                    1                        2
1                    1                        2
2                    1                        2
3                    1                        2
4                    1                        2
..                 ...                      ...
995                  1                        2
996                  1                        2
997                  1                        2
998                  1                        2
999                  1                        2

[1000 rows x 5 columns]
ENDLINE
     Jaringan Komp TP1  Jaringan Komp TP2  Jaringan Komp UTS  \
0                    1                  1                  1
1                    1                  1                  1
2                    1                  1                  1
3                    1                  1                  1
4                    1                  1                  1
..                 ...                ...                ...
995                  1                  1                  1
996                  1                  1                  1
997                  1                  1                  1
998                  1                  1                  1
999                  1                  1                  1

     Jaringan Komp UAS  Jaringan Komp Rata-Rata
0                    1                        2
1                    1                        2
2                    1                        2
3                    1                        2
4                    1                        2
..                 ...                      ...
995                  1                        2
996                  1                        2
997                  1                        2
998                  1                        2
999                  1                        2

[1000 rows x 5 columns]
ENDLINE
     Machine Learning Lanjut TP1  Machine Learning Lanjut TP2  \
0                              1                            1
1                              1                            1
2                              1                            1
3                              1                            1
4                              1                            1
..                           ...                          ...
995                            1                            1
996                            1                            1
997                            1                            1
998                            1                            1
999                            1                            1

     Machine Learning Lanjut UTS  Machine Learning Lanjut UAS  \
0                              1                            1
1                              1                            1
2                              1                            1
3                              1                            1
4                              1                            1
..                           ...                          ...
995                            1                            1
996                            1                            1
997                            1                            1
998                            1                            1
999                            1                            1

     Machine Learning Lanjut Rata-Rata
0                                    2
1                                    2
2                                    2
3                                    2
4                                    2
..                                 ...
995                                  2
996                                  2
997                                  2
998                                  2
999                                  2

[1000 rows x 5 columns]
ENDLINE
     Pemodelan B. Objek TP1  Pemodelan B. Objek TP2  Pemodelan B. Objek UTS  \
0                         1                       1                       1
1                         1                       1                       1
2                         1                       1                       1
3                         1                       1                       1
4                         1                       1                       1
..                      ...                     ...                     ...
995                       1                       1                       1
996                       1                       1                       1
997                       1                       1                       1
998                       1                       1                       1
999                       1                       1                       1

     Pemodelan B. Objek UAS  Pemodelan B. Objek Rata-Rata
0                         1                             2
1                         1                             2
2                         1                             2
3                         1                             2
4                         1                             2
..                      ...                           ...
995                       1                             2
996                       1                             2
997                       1                             2
998                       1                             2
999                       1                             2

[1000 rows x 5 columns]
ENDLINE
     Pengolahan Gbr Data Sci TP1  Pengolahan Gbr Data Sci TP2  \
0                              1                            1
1                              1                            1
2                              1                            1
3                              1                            1
4                              1                            1
..                           ...                          ...
995                            1                            1
996                            1                            1
997                            1                            1
998                            1                            1
999                            1                            1

     Pengolahan Gbr Data Sci TP3  Pengolahan Gbr Data Sci TP4  \
0                              1                            1
1                              1                            1
2                              1                            1
3                              1                            1
4                              1                            1
..                           ...                          ...
995                            1                            1
996                            1                            1
997                            1                            1
998                            1                            1
999                            1                            1

     Pengolahan Gbr Data Sci Rata-Rata
0                                    2
1                                    2
2                                    2
3                                    2
4                                    2
..                                 ...
995                                  2
996                                  2
997                                  2
998                                  2
999                                  2

[1000 rows x 5 columns]
ENDLINE
     Pemrograman Web TP1  Pemrograman Web TP2  Pemrograman Web UTS  \
0                      1                    1                    1
1                      1                    1                    1
2                      1                    1                    1
3                      1                    1                    1
4                      1                    1                    1
..                   ...                  ...                  ...
995                    1                    1                    1
996                    1                    1                    1
997                    1                    1                    1
998                    1                    1                    1
999                    1                    1                    1

     Pemrograman Web UAS  Pemrograman Web Rata-Rata
0                      1                          2
1                      1                          2
2                      1                          2
3                      1                          2
4                      1                          2
..                   ...                        ...
995                    1                          2
996                    1                          2
997                    1                          2
998                    1                          2
999                    1                          2

[1000 rows x 5 columns]
ENDLINE
     Pemrograman Mobile TP1  Pemrograman Mobile TP2  Pemrograman Mobile UTS  \
0                         1                       1                       1
1                         1                       1                       1
2                         1                       1                       1
3                         1                       1                       1
4                         1                       1                       1
..                      ...                     ...                     ...
995                       1                       1                       1
996                       1                       1                       1
997                       1                       1                       1
998                       1                       1                       1
999                       1                       1                       1

     Pemrograman Mobile UAS  Pemrograman Mobile Rata-Rata
0                         1                             2
1                         1                             2
2                         1                             2
3                         1                             2
4                         1                             2
..                      ...                           ...
995                       1                             2
996                       1                             2
997                       1                             2
998                       1                             2
999                       1                             2

[1000 rows x 5 columns]
ENDLINE
     Blockchain TP1  Blockchain TP2  Blockchain UTS  Blockchain UAS  \
0                 1               1               1               1
1                 1               1               1               1
2                 1               1               1               1
3                 1               1               1               1
4                 1               1               1               1
..              ...             ...             ...             ...
995               1               1               1               1
996               1               1               1               1
997               1               1               1               1
998               1               1               1               1
999               1               1               1               1

     Blockchain Rata-Rata
0                       2
1                       2
2                       2
3                       2
4                       2
..                    ...
995                     2
996                     2
997                     2
998                     2
999                     2

[1000 rows x 5 columns]
ENDLINE
    Topik Skripsi
0             TES
1             TES
2             TES
3             TES
4             TES
..            ...
995           TES
996           TES
997           TES
998           TES
999           TES

[1000 rows x 1 columns]
ENDLINE

In [4]:
#imputasi berdasarkan aturan
df.iloc[0,0]=0
#df.iloc[0,1:6]
for i in range(0,len(df)):
    print("--------------------\nTEST: NEW ENTRY\n--------------------")
    for j in range(1,len(df.columns)-5,5):
        print(df.iloc[i,j:j+5])
        print("--------------------------")

--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 0, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 0, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 0, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 0, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 0, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 0, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 0, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 0, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 0, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 0, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 1, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 1, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 1, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 1, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 1, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 1, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 1, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 1, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 1, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 1, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 2, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 2, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 2, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 2, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 2, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 2, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 2, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 2, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 2, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 2, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 3, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 3, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 3, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 3, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 3, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 3, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 3, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 3, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 3, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 3, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 4, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 4, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 4, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 4, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 4, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 4, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 4, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 4, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 4, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 4, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 5, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 5, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 5, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 5, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 5, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 5, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 5, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 5, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 5, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 5, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 6, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 6, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 6, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 6, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 6, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 6, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 6, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 6, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 6, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 6, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 7, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 7, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 7, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 7, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 7, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 7, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 7, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 7, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 7, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 7, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 8, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 8, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 8, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 8, dtype: object
--------------------------
Machine Learning Lanjut TP1          1
Machine Learning Lanjut TP2          1
Machine Learning Lanjut UTS          1
Machine Learning Lanjut UAS          1
Machine Learning Lanjut Rata-Rata    2
Name: 8, dtype: object
--------------------------
Pemodelan B. Objek TP1          1
Pemodelan B. Objek TP2          1
Pemodelan B. Objek UTS          1
Pemodelan B. Objek UAS          1
Pemodelan B. Objek Rata-Rata    2
Name: 8, dtype: object
--------------------------
Pengolahan Gbr Data Sci TP1          1
Pengolahan Gbr Data Sci TP2          1
Pengolahan Gbr Data Sci TP3          1
Pengolahan Gbr Data Sci TP4          1
Pengolahan Gbr Data Sci Rata-Rata    2
Name: 8, dtype: object
--------------------------
Pemrograman Web TP1          1
Pemrograman Web TP2          1
Pemrograman Web UTS          1
Pemrograman Web UAS          1
Pemrograman Web Rata-Rata    2
Name: 8, dtype: object
--------------------------
Pemrograman Mobile TP1          1
Pemrograman Mobile TP2          1
Pemrograman Mobile UTS          1
Pemrograman Mobile UAS          1
Pemrograman Mobile Rata-Rata    2
Name: 8, dtype: object
--------------------------
Blockchain TP1          1
Blockchain TP2          1
Blockchain UTS          1
Blockchain UAS          1
Blockchain Rata-Rata    2
Name: 8, dtype: object
--------------------------
--------------------
TEST: NEW ENTRY
--------------------
Kalkulus 1 TP1          1
Kalkulus TP2            1
Kalkulus 1 UTS          1
Kalkulus 1 UAS          1
Kalkulus 1 Rata-Rata    2
Name: 9, dtype: object
--------------------------
Data Sci IoT TP1          1
Data Sci IoT TP2          1
Data Sci IoT UTS          1
Data Sci IoT UAS          1
Data Sci IoT Rata-Rata    2
Name: 9, dtype: object
--------------------------
Keamanan Komp TP1          1
Keamanan Komp TP2          1
Keamanan Komp UTS          1
Keamanan Komp UAS          1
Keamanan Komp Rata-Rata    2
Name: 9, dtype: object
--------------------------
Jaringan Komp TP1          1
Jaringan Komp TP2          1
Jaringan Komp UTS          1
Jaringan Komp UAS          1
Jaringan Komp Rata-Rata    2
Name: 9, dtype: object

#### Distribusi Nilai
- 75 persen berprestasi
- 25 persen kesulitan

In [5]:
#proof of concept utk data lama
for i in range(0,len(df)):
    
    temp_avg = 0
    #implementasi mahasiswa berprestasi atau kesulitan
    nilai_min = 2 if i%4==0 else 5
    nilai_maks = 10 if i%4==0 else 12
    
    
    #print(nilai_min)
    df.iloc[i,0]=i #no. mahasiswa

    for j in range(1,len(df.columns)-5,5):
        
        tp1 = randint(nilai_min,nilai_maks)
        tp2 = randint(max(1,tp1-4),min(nilai_maks,tp1+4))
        uts = randint(max(1,min(tp1,tp2)-4),min(nilai_maks,min(tp1,tp2)+5))
        uas = randint(max(1,min(tp1,tp2,uts)-4),min(nilai_maks,min(tp1,tp2,uts)+5))

        rata2 = round((tp1+tp2+uts+uas)/4)

        df.iloc[i,j] = tp1
        df.iloc[i,j+1] = tp2 
        df.iloc[i,j+2] = uts
        df.iloc[i,j+3] = uas
        df.iloc[i,j+4] = rata2
        
        #print(tp1, tp2, uts, uas, rata2)

In [6]:
df

,No Mhs,Kalkulus 1 TP1,Kalkulus TP2,Kalkulus 1 UTS,Kalkulus 1 UAS,Kalkulus 1 Rata-Rata,Data Sci IoT TP1,Data Sci IoT TP2,Data Sci IoT UTS,Data Sci IoT UAS,...,Pemrograman Mobile TP2,Pemrograman Mobile UTS,Pemrograman Mobile UAS,Pemrograman Mobile Rata-Rata,Blockchain TP1,Blockchain TP2,Blockchain UTS,Blockchain UAS,Blockchain Rata-Rata,Topik Skripsi
0,0,10,8,8,7,8,9,5,10,8,...,6,2,7,6,2,5,3,2,3,TES
1,1,6,7,2,1,4,12,8,5,8,...,12,9,9,10,8,5,4,7,6,TES
2,2,8,5,3,1,4,7,8,3,3,...,8,8,9,9,11,11,10,6,10,TES
3,3,6,3,3,2,4,6,5,10,4,...,2,5,2,4,12,9,5,7,8,TES
4,4,3,1,1,5,2,5,5,2,7,...,8,3,8,6,2,3,3,6,4,TES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,8,10,12,7,9,7,6,6,9,...,11,9,6,10,6,8,10,11,9,TES
996,996,7,6,3,2,4,10,9,6,10,...,5,7,2,5,6,2,6,5,5,TES
997,997,11,8,6,11,9,10,6,3,8,...,8,4,3,6,9,7,12,4,8,TES
998,998,5,6,5,6,6,5,1,4,3,...,9,8,7,8,12,10,10,12,11,TES
999,999,8,10,9,6,8,7,10,8,6,...,11,7,3,8,6,2,1,1,2,TES

In [7]:
#df.to_csv("dummydata.csv",index=False)

In [8]:
#Topik Skripsi di-random dari 3 top pilihan
rata2 = ['No Mhs']
for i in df.columns:
    
    if(str(i).lower().find('rata-rata')!=-1):
        rata2.append(i)

In [9]:
df_rata2 = df[rata2]
df_rata2

,No Mhs,Kalkulus 1 Rata-Rata,Data Sci IoT Rata-Rata,Keamanan Komp Rata-Rata,Jaringan Komp Rata-Rata,Machine Learning Lanjut Rata-Rata,Pemodelan B. Objek Rata-Rata,Pengolahan Gbr Data Sci Rata-Rata,Pemrograman Web Rata-Rata,Pemrograman Mobile Rata-Rata,Blockchain Rata-Rata
0,0,8,8,4,4,3,6,3,7,6,3
1,1,4,8,6,6,10,10,10,6,10,6
2,2,4,5,5,10,12,6,5,7,9,10
3,3,4,6,9,4,10,9,4,9,4,8
4,4,2,5,8,3,7,2,2,4,6,4
...,...,...,...,...,...,...,...,...,...,...,...
995,995,9,7,6,4,10,7,8,6,10,9
996,996,4,9,3,7,2,8,9,4,5,5
997,997,9,7,4,6,7,6,8,6,6,8
998,998,6,3,11,10,5,10,8,4,8,11
999,999,8,8,6,6,9,11,10,10,8,2

In [10]:
#memilih rekomendasi skripsi - data dummy
#random sort 3 nilai terbaik, ambil mata kuliahnya
for index,row in df_rata2.iterrows():
    row_mhs = dict(row)
    no_mhs = row_mhs['No Mhs']
    del row_mhs['No Mhs']
    
    row_mhs = sorted(row_mhs.items(), key= lambda i:i[1], reverse=True) #Thanks FreeCodeCamp https://www.freecodecamp.org/news/sort-dictionary-by-value-in-python/
    row_mhs = dict(row_mhs)
    
    top_3_nilai = list(row_mhs.keys())[:3]
    topik_skripsi = str(top_3_nilai[randint(0,2)])
    df.loc[index, 'Topik Skripsi'] = topik_skripsi.replace(' Rata-Rata','')
    
df

,No Mhs,Kalkulus 1 TP1,Kalkulus TP2,Kalkulus 1 UTS,Kalkulus 1 UAS,Kalkulus 1 Rata-Rata,Data Sci IoT TP1,Data Sci IoT TP2,Data Sci IoT UTS,Data Sci IoT UAS,...,Pemrograman Mobile TP2,Pemrograman Mobile UTS,Pemrograman Mobile UAS,Pemrograman Mobile Rata-Rata,Blockchain TP1,Blockchain TP2,Blockchain UTS,Blockchain UAS,Blockchain Rata-Rata,Topik Skripsi
0,0,10,8,8,7,8,9,5,10,8,...,6,2,7,6,2,5,3,2,3,Kalkulus 1
1,1,6,7,2,1,4,12,8,5,8,...,12,9,9,10,8,5,4,7,6,Machine Learning Lanjut
2,2,8,5,3,1,4,7,8,3,3,...,8,8,9,9,11,11,10,6,10,Blockchain
3,3,6,3,3,2,4,6,5,10,4,...,2,5,2,4,12,9,5,7,8,Pemodelan B. Objek
4,4,3,1,1,5,2,5,5,2,7,...,8,3,8,6,2,3,3,6,4,Pemrograman Mobile
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,8,10,12,7,9,7,6,6,9,...,11,9,6,10,6,8,10,11,9,Pemrograman Mobile
996,996,7,6,3,2,4,10,9,6,10,...,5,7,2,5,6,2,6,5,5,Pengolahan Gbr Data Sci
997,997,11,8,6,11,9,10,6,3,8,...,8,4,3,6,9,7,12,4,8,Kalkulus 1
998,998,5,6,5,6,6,5,1,4,3,...,9,8,7,8,12,10,10,12,11,Keamanan Komp
999,999,8,10,9,6,8,7,10,8,6,...,11,7,3,8,6,2,1,1,2,Pemodelan B. Objek

In [11]:
df.to_csv("data_dummy_final.csv")